name: capstone
dependencies:
    - python==2.7.12
    - opencv
    - scikit-learn
    - matplotlib
    - pandas
    - pip:
        - Flask>=0.11.1
        - attrdict>=2.0.0
        - eventlet>=0.19.0
        - python-socketio>=1.6.1
        - numpy>=1.13.1
        - Pillow>=2.2.1
        - scipy>=0.13.3
        - keras==2.0.8
        - tensorflow==1.3.0
        - h5py>=2.6.0
        - pygame>=1.9.3
